### ISSUE TITLE
fetching html failed

### ISSUE THREAD

**Issue by Smile-L** [flexwang/BaiduImageCrawler#1]
thanks for your code.

i run it .but i got "fetching html failed"

how can i fix it?

**Comment by flexwang-zz** [comment]
@lisiminy Would you mind providing the parameters you ran?

**Comment by Smile-L** [comment]
i used 
"python crawls.py pets d:/pets 40 1"
do you mean this paramters?
thx

**Comment by flexwang-zz** [comment]
@lisiminy
I just ran 'python crawler.py pets d:/pets 40 1', and it worked fine with me.
According to the code, _fetching html failed_ happens when you have trouble accessing [http://images.baidu.com](http://images.baidu.com). Would you mind checking your network?

**Comment by eriche2016** [comment]
@flexwang check this one. https://github.com/eriche2016/BaiduImageCrawler2
